### ISSUE TITLE
We need a CoC

### ISSUE THREAD

**Issue by cheapwebmonkey** [civicdata/civicdata.github.io-old#33]
Which of these is most suitable? 
https://github.com/civicdata/civicdata.github.io/community/code-of-conduct/new?template=citizen-code-of-conduct or
https://github.com/civicdata/civicdata.github.io/community/code-of-conduct/new?template=contributor-covenant

**Comment by rkahne** [comment]
These seem very similar.  I can't find any major differences.  They both seem fine.

**Comment by thebouv** [comment]
Yeah, I'm confused, aren't these the same?

**Comment by cheapwebmonkey** [comment]
sorry- it was late. diff link is: https://github.com/civicdata/civicdata.github.io/community/code-of-conduct/new?template=contributor-covenant

**Comment by cheapwebmonkey** [comment]
I think we're should go with the citizen coc vs the contrib coc
